import Head from 'next/head'
import About from '../components/HomeComponents/About'
import Header from '../components/HomeComponents/Header'
import Projects from '../components/HomeComponents/Projects'
import Services from '../components/HomeComponents/Services'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <About />
        <Projects />
        <Services />
      </main>
    </div>
  )
}
